# Домашнее задание "Основные математические понятия".

## Уровень 0:


Представим фильмы в виде бинарных векторов (numpy array) используя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

[Игра в имитацию](https://www.kinopoisk.ru/film/635772/)

[Ярость](https://www.kinopoisk.ru/film/740644/)

[12 лет рабства](https://www.kinopoisk.ru/film/606646/)

[Однажды в Голливуде](https://www.kinopoisk.ru/film/1047883/)

```
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию

film_2 = np.array([0,1,0,1,0,0])      # Ярость

film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства

film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде
```



In [30]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

In [31]:
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию
film_2 = np.array([0,1,0,1,0,0])      # Ярость
film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства
film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде

### Задание 1

Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [32]:
# скалярное произведение вектора

sk = dot(film_2, film_3)

In [33]:
# евклидова норма векторов 
n_film_2 = norm(film_2)
n_film_3 = norm(film_3)

In [34]:
# косинус угла между двумя векторами

TH = sk / (n_film_2 * n_film_3)
TH

0.40824829046386296

## Уровень 1:

### Задание 2

Вычислить с помощью Python значение первой производной для функции $8x(x+3)^2$ в точке $x=1$


In [35]:
import sympy as sym

In [36]:
x = sym.Symbol('x') # аналитический символ

In [37]:
8 * x * (x + 3) ** 2

8*x*(x + 3)**2

In [38]:
# продифиренцируем функцию по х

res = sym.diff(8 * x * (x + 3) ** 2, x)
res

8*x*(2*x + 6) + 8*(x + 3)**2

In [39]:
# значение производной в точке x = 1
res.subs(x, 1)

192

### Задание 3


Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы. Умножьте вектор [1,2,3,4] на полученную матрицу

In [43]:
film_total = np.array((film_1, film_2, film_3, film_4))
film_total

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1]])

In [44]:
vect = np.array([1, 2, 3, 4])

In [48]:
dot(vect, film_total)

array([4, 2, 3, 9, 4, 4])

In [50]:
# Либо второй способ используем оператор @ 
vect @ film_total

array([4, 2, 3, 9, 4, 4])